/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.gbif.cube.gmap.density.backfill.io;  
@SuppressWarnings("all")
public enum TileType { 
  TAXON, DATASET  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TileType\",\"namespace\":\"org.gbif.cube.gmap.density.backfill.io\",\"symbols\":[\"TAXON\",\"DATASET\"]}");
}
