/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.gbif.cube.gmap.density.ops;  
@SuppressWarnings("all")
public class Tile extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Tile\",\"namespace\":\"org.gbif.cube.gmap.density.model\",\"fields\":[{\"name\":\"pixels\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Pixel\",\"fields\":[{\"name\":\"x\",\"type\":\"int\"},{\"name\":\"y\",\"type\":\"int\"},{\"name\":\"count\",\"type\":\"int\"}]}}]}]}");
  @Deprecated public java.util.List<org.gbif.cube.gmap.density.ops.Pixel> pixels;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return pixels;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: pixels = (java.util.List<org.gbif.cube.gmap.density.ops.Pixel>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'pixels' field.
   */
  public java.util.List<org.gbif.cube.gmap.density.ops.Pixel> getPixels() {
    return pixels;
  }

  /**
   * Sets the value of the 'pixels' field.
   * @param value the value to set.
   */
  public void setPixels(java.util.List<org.gbif.cube.gmap.density.ops.Pixel> value) {
    this.pixels = value;
  }

  /** Creates a new Tile RecordBuilder */
  public static org.gbif.cube.gmap.density.ops.Tile.Builder newBuilder() {
    return new org.gbif.cube.gmap.density.ops.Tile.Builder();
  }
  
  /** Creates a new Tile RecordBuilder by copying an existing Builder */
  public static org.gbif.cube.gmap.density.ops.Tile.Builder newBuilder(org.gbif.cube.gmap.density.ops.Tile.Builder other) {
    return new org.gbif.cube.gmap.density.ops.Tile.Builder(other);
  }
  
  /** Creates a new Tile RecordBuilder by copying an existing Tile instance */
  public static org.gbif.cube.gmap.density.ops.Tile.Builder newBuilder(org.gbif.cube.gmap.density.ops.Tile other) {
    return new org.gbif.cube.gmap.density.ops.Tile.Builder(other);
  }
  
  /**
   * RecordBuilder for Tile instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Tile>
    implements org.apache.avro.data.RecordBuilder<Tile> {

    private java.util.List<org.gbif.cube.gmap.density.ops.Pixel> pixels;

    /** Creates a new Builder */
    private Builder() {
      super(org.gbif.cube.gmap.density.ops.Tile.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.gbif.cube.gmap.density.ops.Tile.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Tile instance */
    private Builder(org.gbif.cube.gmap.density.ops.Tile other) {
            super(org.gbif.cube.gmap.density.ops.Tile.SCHEMA$);
      if (isValidValue(fields()[0], other.pixels)) {
        this.pixels = (java.util.List<org.gbif.cube.gmap.density.ops.Pixel>) data().deepCopy(fields()[0].schema(), other.pixels);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'pixels' field */
    public java.util.List<org.gbif.cube.gmap.density.ops.Pixel> getPixels() {
      return pixels;
    }
    
    /** Sets the value of the 'pixels' field */
    public org.gbif.cube.gmap.density.ops.Tile.Builder setPixels(java.util.List<org.gbif.cube.gmap.density.ops.Pixel> value) {
      validate(fields()[0], value);
      this.pixels = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'pixels' field has been set */
    public boolean hasPixels() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'pixels' field */
    public org.gbif.cube.gmap.density.ops.Tile.Builder clearPixels() {
      pixels = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public Tile build() {
      try {
        Tile record = new Tile();
        record.pixels = fieldSetFlags()[0] ? this.pixels : (java.util.List<org.gbif.cube.gmap.density.ops.Pixel>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
